name: app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.2
  path: ^1.9.0
  image_picker: ^1.0.7
  video_player: ^2.2.11
  get: ^4.6.6

  cupertino_icons: ^1.0.6
  firebase_core: ^2.27.2
  firebase_storage: ^11.6.11
  uuid: ^4.3.3
  video_compress: ^3.1.0
  geolocator: ^11.0.0
  url_launcher: ^6.2.5
  permission_handler: ^11.3.1
  firebase_messaging: ^14.7.21

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true